/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SemestersRouteImport } from './routes/semesters'
import { Route as SemesterSemIndexRouteImport } from './routes/semester.$sem.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemestersRoute = SemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemIndexRoute = SemesterSemIndexRouteImport.update({
  id: '/semester/$sem/',
  path: '/semester/$sem/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRoute
  '/semester/$sem/': typeof SemesterSemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRoute
  '/semester/$sem': typeof SemesterSemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRoute
  '/semester/$sem/': typeof SemesterSemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/semesters' | '/semester/$sem/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/semesters' | '/semester/$sem'
  id: '__root__' | '/' | '/semesters' | '/semester/$sem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SemestersRoute: typeof SemestersRoute
  SemesterSemIndexRoute: typeof SemesterSemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semesters': {
      id: '/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof SemestersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$sem/': {
      id: '/semester/$sem/'
      path: '/semester/$sem'
      fullPath: '/semester/$sem/'
      preLoaderRoute: typeof SemesterSemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SemestersRoute: SemestersRoute,
  SemesterSemIndexRoute: SemesterSemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
